pipeline {
    agent any

    environment {
        IMAGE_NAME = "api-gateway"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Asadullah-nadeem/Microservices-using-CashFree.git'
            }
        }

        stage('Build Application') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:${env.BUILD_NUMBER}", ".")
                }
            }
        }

        stage('Deploy Locally') {
            steps {
                script {
                    sh "docker stop ${IMAGE_NAME} || true"
                    sh "docker rm ${IMAGE_NAME} || true"
                    echo "Starting container ${IMAGE_NAME} on port 8080..."
                    sh "docker run -d --name ${IMAGE_NAME} -p 8080:8080 ${IMAGE_NAME}:${env.BUILD_NUMBER}"
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
